4th assignment
30th-THE-SOPT-iOS-Part/HanYuJin pull request #10
Opened 2022-05-14 13:31 UTC by yujindonut

## 🌱 작업한 내용

- 회원가입 서버통신
- 로그인 서버통신
- Alert창 띄우기 

## 🌱 PR Point

Auto Layout 설정하는 것이 어려워요!
사진마다 , text 크기에 따라서 테이블뷰가 동적으로 넓어지게 설정을 해줬습니다. 근데 이렇게 사진이랑 라벨 사이가 이상하게 띄어짐이 생기게 되어요! 어떤식으로 변경을 해줘야지 이러한 이상한 띄어짐을 없앨 수 있을까요?
전체를 stackview로 주었는데, 이게 문제인걸가요?

| :----------: | :-----------: | 
|
![Simulator Screen Shot - iPhone 13 mini - 2022-05-14 at 22 22 17](https://user-images.githubusercontent.com/78431728/168427768-73e5b2b7-e1cc-492b-8f98-cce8d57b3db5.png)
  | ![Simulator Screen Shot - iPhone 13 mini - 2022-05-14 at 22 22 04](https://user-images.githubusercontent.com/78431728/168427756-70a510f1-b8b7-4944-9ad6-bb279d56fea4.png)
 |

## 📸 스크린샷

### 1. 기본과제 : table view와 collection view 

| `회원가입` | `로그인` | ` 로그인 실패 ` |
| :-------------: | :----------: | :----------: |
| ![Simulator Screen Recording - iPhone 13 mini - 2022-05-14 at 21 37 54](https://user-images.githubusercontent.com/78431728/168427866-2fa90347-74e4-450e-ad18-5a92a81f4c37.gif)
| ![Simulator Screen Recording - iPhone 13 mini - 2022-05-14 at 21 37 13](https://user-images.githubusercontent.com/78431728/168427870-8ae8e538-89b0-43c3-a26e-303ca310a58c.gif)
| ![Simulator Screen Recording - iPhone 13 mini - 2022-05-14 at 21 38 15](https://user-images.githubusercontent.com/78431728/168427877-c0350948-6514-4a52-a89b-af7112483e8b.gif) |

## 📮 관련 이슈

- Resolved: #9

2022-05-16 05:51 UTC, 88yhtserof reviewed
4차 과제도 수고하셨어요!!! 
과제를 하시고 UI도 계속 개선하시고,, 멋져요,,😍

2022-05-16 05:51 UTC, 88yhtserof commented on Instagram-Clone/Instagram-Clone/Global/Extension/UIImage+.swift
> +    }
이렇게 하면 사진이 차지하는 메모리의 크기가 줄어드는건가요?

2022-05-16 05:51 UTC, 88yhtserof commented on Instagram-Clone/Instagram-Clone/Network/Service/UserService.swift
> +    private func isVaildData(data: Data) -> NetworkResult<Any> {
함수 이름에 signIn이 들어가 있으면 로그인 관련한 함수라는 게 잘 드러날 것 같아요!!🙆🏻‍♀️

2022-05-16 06:51 UTC, devxsby requested changes
짜란다짜란다울애깅. ❤️🧡💛💚💙💜

> Auto Layout 설정하는 것이 어려워요! 사진마다 , text 크기에 따라서 테이블뷰가 동적으로 넓어지게 설정을 해줬습니다. 근데 이렇게 사진이랑 라벨 사이가 이상하게 띄어짐이 생기게 되어요! 어떤식으로 변경을 해줘야지 이러한 이상한 띄어짐을 없앨 수 있을까요? 전체를 stackview로 주었는데, 이게 문제인걸가요?

대충 보니까 content 라벨의 Vertical 오토레이아웃을 안 주신것 같아요. 
다른 오브젝트들도 그런 것 같은데,, 오토레이웃을 정확히 묶어주는게 중요하더라구요.
한 번 확인해보시겠어요~??!

2022-05-16 06:51 UTC, devxsby commented on Instagram-Clone/Instagram-Clone/Global/Extension/UIImage+.swift
> +    //사진의 메모리를 줄여주는 코드
? ? ? ? ?
한유진씨는 앞으로 무작정 쇽삭 금지입니다. 🫥

2022-05-16 06:51 UTC, devxsby commented on Instagram-Clone/Instagram-Clone/Network/Service/UserService.swift
> +        case ..<300 : return isVaildData(data: data)
`200...300`으로 쓰는게 어떨까용...?~

2022-05-16 06:51 UTC, devxsby commented on Instagram-Clone/Instagram-Clone/Network/Service/UserService.swift
> +        print("성공은 해서 signupvaliddata에 들어옴")
대견해.

2022-05-16 06:51 UTC, devxsby commented on Instagram-Clone/Instagram-Clone/Source/Screen/Auth/Controller/CompleteController.swift
> +        }
signup 함수에 name, password 합쳐서 선언해주는게 조금 더 깔끔할 것 같아요!!
signup() 만 한 줄만 선언하면 되니까유~~!
그래두 파라미터로 넘기는거도 좋고 잘하시네용 👍

2022-05-16 06:51 UTC, devxsby commented on Instagram-Clone/Instagram-Clone/Source/Screen/Auth/Controller/LoginController.swift
> +                self.alertLoginFail(message: "로그인 실패")
에러 메시지 status code에 따라 나눠서 alert 해주는 것도 좋아보입니다~~!

2022-05-16 06:51 UTC, devxsby commented on Instagram-Clone/Instagram-Clone/Source/Screen/Tabbar/HomeTab/View/FeedTableViewCell.swift
> +        let contentFontAttr: [NSMutableAttributedString.Key: Any] = [
오 폰트 커스텀까지 ~ 디테일 굿굿입니다요 😇

2022-05-16 08:22 UTC, inuinseoul approved these changes
주석 꼼꼼하게 달면서 학습해나가시는거 너무 멋지네요!!
잘봤습니다 :)

2022-05-16 08:22 UTC, inuinseoul commented on Instagram-Clone/Instagram-Clone/Source/Screen/Tabbar/HomeTab/Model/FeedDataModel.swift
> +        FeedDataModel(authorImageName: "avatar6", feedImageName: "postImage6", likes: 60, author: "avatar1", content: "기회는 일어나는 것이 아니라 만들어내는 것이다.기회는 일어나는 것이 아니라 만들어내는 것이다.기회는 일어나는 것이 아니라 만들어내는 것이다.기회
명심하겠습니다..

2022-05-16 08:33 UTC, yujindonut commented on Instagram-Clone/Instagram-Clone/Global/Extension/UIImage+.swift
> +    //사진의 메모리를 줄여주는 코드
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 엉엉 그말이 그말을 적으려고 한게 아니였슴니다 ,, 쇽샥쇽샥맨

2022-05-16 08:34 UTC, yujindonut commented on Instagram-Clone/Instagram-Clone/Network/Service/UserService.swift
> +        case ..<300 : return isVaildData(data: data)
수정하겠습니다 ..

2022-05-16 08:34 UTC, yujindonut commented on Instagram-Clone/Instagram-Clone/Network/Service/UserService.swift
> +        print("성공은 해서 signupvaliddata에 들어옴")
저런거 다 꼼꼼히 보는 언니 대단해 . 저거 왜 안지워지고 저기있쥐

2022-05-16 08:35 UTC, yujindonut commented on Instagram-Clone/Instagram-Clone/Source/Screen/Auth/Controller/CompleteController.swift
> +        }
아! 그렇게 하는게 더 깔끔하겠네요! ❤️‍🔥🔥 칭찬까지 해주는 언니 .. 뭐야 .. 이언니 .. ❤️‍🔥

2022-05-16 08:36 UTC, yujindonut commented on Instagram-Clone/Instagram-Clone/Source/Screen/Auth/Controller/LoginController.swift
> +                self.alertLoginFail(message: "로그인 실패")
수빈언니 대문자 코드 쇽샥쇽샥

2022-05-16 08:36 UTC, yujindonut commented on Instagram-Clone/Instagram-Clone/Source/Screen/Tabbar/HomeTab/View/FeedTableViewCell.swift
> +        let contentFontAttr: [NSMutableAttributedString.Key: Any] = [
민재오빠 쇽샥쇽샥 ,,,

2022-05-16 08:38 UTC, yujindonut commented on Instagram-Clone/Instagram-Clone/Global/Extension/UIImage+.swift
> +    }
제가 잘 못썼습니다 .... 🥹string으로 이미지 이름을 받아온거를 ui image로 처리해주는 함수라고 합니다! 그리고 resize함수는 이미지 비율에 맞게 크기를 줄여주는 함수라고 합니다!!!!!

2022-05-16 08:38 UTC, yujindonut commented on Instagram-Clone/Instagram-Clone/Network/Service/UserService.swift
> +    private func isVaildData(data: Data) -> NetworkResult<Any> {
바로 수정 해버리겠습니다 ,, 💜 꼼꼼 윤휘,, 감사해요 ,,

2022-05-16 11:03 UTC, devxsby commented on Instagram-Clone/Instagram-Clone/Source/Screen/Auth/Controller/LoginController.swift
> +                self.alertLoginFail(message: "로그인 실패")
ㅋㅋㅋㅋㅋ진짴ㅋㅋㅋㅋ샥쇽샥쇽

2022-05-18 08:08 UTC, jeongkite reviewed
extension 쓰는거나 함수에 private 붙이는거 꼼꼼하게 너무 잘 지켜서 해주고 있어서 잘 보고 갑니당.. 짱코드 짱솜배...!!!!!!🥺👍 저두 담부턴 extension 열쉬미 활용해봐야겠어요😙

2022-06-17 10:43 UTC, merged